services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      
  redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379'
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $${{secrets.MYSQL_ROOT_PASSWORD}}
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD= $${{secrets.CASSANDRA_PASSWORD}}
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  redis-data:
  mysql-data:
  cassandra-data:


